### ISSUE TITLE
Map list not working

### ISSUE THREAD

**Issue by dudleycodes** [LacledesLAN/gamesvr-jk2outcast-freeplay#1]
Just repeats the same map over and over.

**Comment by JustinBenedick** [comment]
Found the varible its g_automapcycle 1

https://github.com/LacledesLAN/gamesvr-jk2outcast-freeplay/commit/9217f47823f66e1d7053850ef44f749368e0b039

**Comment by dudleycodes** [comment]
issue verified fixed; closing

**Comment by dudleycodes** [comment]
Issue was fixed in commit bc66de698e627d24e51821d8a456eec3a74ee716
