### ISSUE TITLE
duel frag limits are too high

### ISSUE THREAD

**Issue by dudleycodes** [LacledesLAN/gamesvr-jk2outcast-freeplay#2]
let's set it to `5` for w/ weapons and `3` for w/o.

**Comment by JustinBenedick** [comment]
updated frag limits on duels 

https://github.com/LacledesLAN/gamesvr-jk2outcast-freeplay/commit/9217f47823f66e1d7053850ef44f749368e0b039

**Comment by dudleycodes** [comment]
issue fixed as of bc66de698e627d24e51821d8a456eec3a74ee716
